# Generated by Django 3.2.4 on 2021-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
