# Generated by Django 3.2.4 on 2021-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_mymodel_boolean_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
