# Generated by Django 3.2.4 on 2021-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_mymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
